# generated by datamodel-codegen:
#   filename:  v1.json
#   timestamp: 2024-03-17T14:35:10+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel
from typing_extensions import Literal


class UserRole(Enum):
    admin = 'admin'
    manager = 'manager'
    employee = 'employee'


class AccountRoleChangedData(BaseModel):
    user_public_id: str
    new_role: UserRole


class AccountRoleChangedEvent(BaseModel):
    event_id: str
    event_version: Literal[1] = 1
    event_name: Literal['AccountRoleChanged'] = 'AccountRoleChanged'
    event_time: datetime
    producer: str
    data: AccountRoleChangedData
